### ISSUE TITLE
tweetに位置情報を設定する

### ISSUE THREAD

**Issue by matsubo** [matsubo/covid19-daily-tweet#8]

**Comment by matsubo** [comment]
place_idを取れない
```
irb(main):053:0> twitter.geo_search('lat' =>  '37.781157', 'long' =>  '-122.398720')
Traceback (most recent call last):
       16: from /usr/local/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
       15: from /usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
       14: from /usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
       13: from /usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
       12: from /usr/local/bin/irb:23:in `<top (required)>'
       11: from /usr/local/bin/irb:23:in `load'
       10: from /usr/local/lib/ruby/gems/2.7.0/gems/irb-1.2.3/exe/irb:11:in `<top (required)>'
        9: from (irb):52
        8: from (irb):53:in `rescue in irb_binding'
        7: from /usr/local/bundle/gems/twitter-7.0.0/lib/twitter/rest/places_and_geo.rb:59:in `geo_search'
        6: from /usr/local/bundle/gems/twitter-7.0.0/lib/twitter/rest/utils.rb:57:in `perform_get_with_object'
        5: from /usr/local/bundle/gems/twitter-7.0.0/lib/twitter/rest/utils.rb:72:in `perform_request_with_object'
        4: from /usr/local/bundle/gems/twitter-7.0.0/lib/twitter/rest/utils.rb:50:in `perform_request'
        3: from /usr/local/bundle/gems/twitter-7.0.0/lib/twitter/rest/request.rb:39:in `perform'
        2: from /usr/local/bundle/gems/http-4.4.1/lib/http/response.rb:158:in `parse'
        1: from /usr/local/bundle/gems/http-4.4.1/lib/http/mime_type.rb:38:in `[]'
HTTP::Error (Unknown MIME type: text/plain)
```

しかも都道府県レベルの粒度で取れないから、いらないかな。
